### ISSUE TITLE
Support for armv7

### ISSUE THREAD

**Issue by sblcook** [python-sdbus/python-sdbus#43]
Is it possible to create a build target for armv7 architecture? I see that you mention it would be possible i686, ppc64le and s390x but armv7 isn't mentioned.

Thanks!

**Comment by igo95862** [comment]
Hello @sblcook 

The issue is there is no ARMv7 manylinux container image: https://github.com/pypa/manylinux#manylinux2014-centos-7-based

See: https://github.com/pypa/manylinux/issues/84

However, it should still be possible to build python-sdbus from source on ARMv7 given that all dependencies are met.

**Comment by sblcook** [comment]
Thanks, that's too bad. I looked into building from source, but ended up going another route.

**Comment by igo95862** [comment]
I plan on experimenting with completely static linked wheels. Maybe it will make it possible to build any architecture without relying on PyPA container images.

**Comment by igo95862** [comment]
@sblcook version 0.14.0 now have the `armv7l` wheels published to PyPI.
