### ISSUE TITLE
Public API for object paths

### ISSUE THREAD

**Issue by sassanh** [python-sdbus/python-sdbus#67]
Thanks for this useful Python package!

I'm using this method [`add_and_activate_connection`](https://python-sdbus-networkmanager.readthedocs.io/en/latest/other_interfaces.html#sdbus_async.networkmanager.NetworkManagerInterfaceAsync.add_and_activate_connection) and it needs object paths as its parameters, currently I'm getting object paths from `.dbus.object_path` but this not the public and official API and subject to change.

So as you suggested [here](https://github.com/ubopod/ubo_app/issues/57#issuecomment-2093453433) I would like to discuss the possibility of a public API for getting object paths.

An alternative would be making `add_and_activate_connection` work directly with sdbus objects, or generally allowing sdbus objects to be passed when an object path parameter is required.

**Comment by igo95862** [comment]
Hello @sassanh 

> Thanks for this useful Python package!

I am glad you like it.

> An alternative would be making `add_and_activate_connection` work directly with sdbus objects, or generally allowing sdbus objects to be passed when an object path parameter is required.

Interesting idea. Right now the `o` D-Bus type is a simple string. I will investigate if it possible to make it accept objects without breaking backwards compatibility.

Right now the issue is that there are two different `._dbus` that an object can have. There is the local metadata or a proxy metadata. Because in python-sdbus same class is used for both local objects and proxies it can be either one of them. This is futher complicated by the fact the local object should able to be exported to multiple D-Buses. (current impossible but this just not implemented yet) 

Maybe there can be a function `sdbus.utils.get_dbus_object_path(dbus_object, bus=None)`. When called on a local object it will retrieve the exported path on a given bus (or default bus) or raise an exception if was not exported on a given path. When called on proxy will retrieve the proxied path on a given bus or raise exception if the proxy is not attached to a given bus.

**Comment by igo95862** [comment]
I started with a new function `sdbus.utils.inspect.inspect_dbus_path` in 498663fc1c93b5b4ed8dbbc383442953f1bb42fa. Right now it raises LookupErrors when for example called on a local object that was not exported but I might change that to None.

**Comment by sassanh** [comment]
Hi @igo95862

Thanks! I just tried this and it works very well for my use-cases.

**Comment by igo95862** [comment]
Added in edf2404a720e2238682f4937781f2b36988eba6d
